# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux/Qt5']
   'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/frameworkintegration': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kguiaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/kirigami': '@latest'
    'frameworks/kwindowsystem': '@latest'

 - 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6', 'Linux/Qt6Next']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kguiaddons': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kcolorscheme': 'Frameworks/6.24'

 - 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Linux/Qt6Next']
   'require':
    'plasma/kdecoration': '@same'
    'frameworks/frameworkintegration': 'Frameworks/6.24'
    'frameworks/kcmutils': 'Frameworks/6.24'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
