/* config-breeze.h. Generated by cmake from config-breeze.h.cmake */

/*
 * SPDX-FileCopyrightText: 2014 Hugo Pereira Da Costa <hugo.pereira@free.fr>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#pragma once

/* Define to 1 if QtQuick is available */
#cmakedefine01 BREEZE_HAVE_QTQUICK

/* Define to 1 if FrameworkIntegration/Kstyle libraries are found */
#cmakedefine01 BREEZE_HAVE_KSTYLE

#cmakedefine01 HAVE_QTDBUS
